name: Generate Cypress Report
on:
  push:
    branches:
      - 'cypress3'

jobs:
  cypress-test:
    name: Run on Chrome 107
    runs-on: ubuntu-20.04
    container: cypress/browsers:node16.16.0-chrome107-ff107

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

      - name: Install cypress and verify
        run: |
          npm ci
          $(npm bin)/cypress verify
      - name: Run Cypress tests
        run: npm run test:chrome
        continue-on-error: true

      - name: Copy test execution videos and screenshots
        run: |
          mkdir public
          cp -r public/videos
          cp -r public/screenshots
      - name: Merge test reports
        run: npm run combine:report

      - name: Generate HTML report
        run: npm run generate:report

      - name: Deploy report page to GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
