name: Cypress Test
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - master
  pull_request:
    branches: ['master']

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Cypress.io
        uses: cypress-io/github-action@v5.0.0
        with:
          browser: chrome
